import type { ComponentCategory, ComponentDef, ComponentKind } from "./types";

export const COMPONENT_DEFS: Record<ComponentKind, ComponentDef> = {
  client: {
    kind: "client",
    label: "Client",
    category: "entry",
    icon: "Monitor",
    color: "#64748b",
    capacity: {},
    latency: { baseMs: 1 },
    consistency: "n/a",
    scaling: "managed",
    configFields: [],
  },
  lb: {
    kind: "lb",
    label: "Load balancer",
    category: "network",
    icon: "Scale",
    color: "#0ea5e9",
    capacity: { rps: 100000 },
    latency: { baseMs: 1 },
    consistency: "n/a",
    scaling: "managed",
    configFields: [],
  },
  api_gateway: {
    kind: "api_gateway",
    label: "API gateway",
    category: "network",
    icon: "Waypoints",
    color: "#06b6d4",
    capacity: { rps: 50000 },
    latency: { baseMs: 3 },
    consistency: "n/a",
    scaling: "managed",
    configFields: [],
  },
  cdn: {
    kind: "cdn",
    label: "CDN",
    category: "network",
    icon: "Globe",
    color: "#14b8a6",
    capacity: {},
    latency: { baseMs: 15 },
    consistency: "eventual",
    scaling: "managed",
    configFields: [
      {
        key: "hitRate",
        label: "Hit rate",
        type: "number",
        min: 0,
        max: 0.95,
        step: 0.05,
        default: 0.9,
      },
    ],
  },
  app_server: {
    kind: "app_server",
    label: "App server",
    category: "compute",
    icon: "Server",
    color: "#6366f1",
    capacity: { rps: 4000 },
    latency: { baseMs: 8 },
    consistency: "n/a",
    scaling: "horizontal",
    configFields: [
      {
        key: "replicas",
        label: "Replicas",
        type: "number",
        min: 1,
        max: 50,
        step: 1,
        default: 1,
      },
    ],
  },
  worker: {
    kind: "worker",
    label: "Worker",
    category: "compute",
    icon: "Cog",
    color: "#8b5cf6",
    capacity: { rps: 1000 },
    latency: { baseMs: 20 },
    consistency: "n/a",
    scaling: "horizontal",
    configFields: [
      {
        key: "replicas",
        label: "Replicas",
        type: "number",
        min: 1,
        max: 50,
        step: 1,
        default: 1,
      },
    ],
  },
  cache: {
    kind: "cache",
    label: "Cache",
    category: "storage",
    icon: "Zap",
    color: "#f59e0b",
    capacity: { rps: 100000, writeRps: 100000 },
    latency: { baseMs: 1 },
    consistency: "eventual",
    scaling: "horizontal",
    configFields: [
      {
        key: "replicas",
        label: "Replicas",
        type: "number",
        min: 1,
        max: 20,
        step: 1,
        default: 1,
      },
      {
        key: "hitRate",
        label: "Hit rate",
        type: "number",
        min: 0,
        max: 0.95,
        step: 0.05,
        default: 0.8,
      },
    ],
  },
  db_sql: {
    kind: "db_sql",
    label: "SQL database",
    category: "storage",
    icon: "Database",
    color: "#3b82f6",
    capacity: {
      rps: 30000,
      writeRps: 15000,
      storageGb: 1000,
      connections: 500,
    },
    latency: { baseMs: 5 },
    consistency: "strong",
    scaling: "vertical",
    configFields: [
      {
        key: "replicas",
        label: "Read replicas",
        type: "number",
        min: 0,
        max: 5,
        step: 1,
        default: 0,
      },
      { key: "sharded", label: "Sharded", type: "boolean", default: false },
    ],
  },
  db_nosql: {
    kind: "db_nosql",
    label: "NoSQL database",
    category: "storage",
    icon: "DatabaseZap",
    color: "#10b981",
    capacity: { rps: 50000, writeRps: 30000 },
    latency: { baseMs: 3 },
    consistency: "eventual",
    scaling: "horizontal",
    configFields: [
      {
        key: "replicas",
        label: "Nodes",
        type: "number",
        min: 1,
        max: 50,
        step: 1,
        default: 3,
      },
      {
        key: "consistencyMode",
        label: "Consistency",
        type: "select",
        options: ["eventual", "quorum", "strong"],
        default: "eventual",
      },
    ],
  },
  blob: {
    kind: "blob",
    label: "Blob store",
    category: "storage",
    icon: "HardDrive",
    color: "#737373",
    capacity: {},
    latency: { baseMs: 50 },
    consistency: "strong",
    scaling: "managed",
    configFields: [],
  },
  search: {
    kind: "search",
    label: "Search index",
    category: "storage",
    icon: "Search",
    color: "#d946ef",
    capacity: { rps: 10000, writeRps: 2000 },
    latency: { baseMs: 20 },
    consistency: "eventual",
    scaling: "horizontal",
    configFields: [
      {
        key: "replicas",
        label: "Replicas",
        type: "number",
        min: 1,
        max: 20,
        step: 1,
        default: 1,
      },
    ],
  },
  queue: {
    kind: "queue",
    label: "Queue",
    category: "async",
    icon: "ListOrdered",
    color: "#f97316",
    capacity: { rps: 800000 },
    latency: { baseMs: 4 },
    consistency: "n/a",
    scaling: "managed",
    configFields: [],
  },
  stream: {
    kind: "stream",
    label: "Stream",
    category: "async",
    icon: "Waves",
    color: "#e11d48",
    capacity: { rps: 800000 },
    latency: { baseMs: 4 },
    consistency: "n/a",
    scaling: "managed",
    configFields: [],
  },
};

export const COMPONENT_KINDS = Object.keys(COMPONENT_DEFS) as ComponentKind[];

export const CATEGORY_ORDER: ComponentCategory[] = [
  "entry",
  "network",
  "compute",
  "storage",
  "async",
];

export function getComponentDef(kind: ComponentKind): ComponentDef {
  return COMPONENT_DEFS[kind];
}
